version: '3.8'
services:
  app:
    build: .
    container_name: genai_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./app.py:/app/app.py
      - ./modules:/app/modules
      - ./handlers:/app/handlers
      - ./charts:/app/charts
      - ./data_sources:/app/data_sources

    environment:
      - PYTHONUNBUFFERED=1